sudo: required

language: ruby

services:
  - docker

before_install:
  - docker run -d --rm --name mongodb -p 27017:27017 mongo
  - docker build -t business-day-api .
  - docker run -d --rm --name business-day-service -p 9292:9292 --link mongodb:mongodb business-day-api
  - docker ps -a

script:
  - docker exec business-day-service /bin/sh -c "cd /usr/src/app; bundle exec rspec"

deploy:
- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  application: BusinessDaysCodeDeploy
  deployment_group: TravisDeploy
  region: us-east-1
  on:
    branch: develop
