version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app
permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
  - object: /home/ubuntu/app/deploy.sh
    mode: 755
    type:
      - file
hooks:
  AfterInstall:
    - location: /home/ubuntu/app/deploy.sh
      timeout: 300
