version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app
permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
  - object: /cd/
    pattern: "*.sh"
    owner: ubuntu
    mode: 755
    type:
      - file
hooks:
  AfterInstall:
    - location: ./cd/deploy.sh
      runas: ubuntu
