development:
  clients:
    default:
      database: business_days
      hosts:
        - localhost:27017
production:
  clients:
    default:
      database: business_days
      hosts:
        - mongodb:27017
